### ISSUE TITLE
这个支持react native吗？

### ISSUE THREAD

**Issue by WaterEye0o** [starlight36/fetch-http-client#1]

**Comment by starlight36** [comment]
目前这个库支持React Native和浏览器中使用，不支持node。在ReactNative中即引即用。在浏览器中使用，为了使其兼容老版本浏览器，请添加[fetch-polyfill](https://www.npmjs.com/package/fetch-polyfill)。

**Comment by WaterEye0o** [comment]
@starlight36 谢谢，可以留个联系方式吗？我也是大连的

**Comment by starlight36** [comment]
新浪微博：[@starlight36](http://weibo.com/starlight36)  微信：`starlight36`
