### ISSUE TITLE
throw error on error codes

### ISSUE THREAD

**Issue by cyberhck** [starlight36/fetch-http-client#5]
Right now, everything comes in .then block, if the response code was more or equal to 400, we want to throw a error hence promise should be rejected.

**Comment by starlight36** [comment]
Non-success response is not treated as exception because `fetch` has the same behaviors. But you can use a middleware to do some workaround such as:

```js
client.addMiddleware(request => response => {
  if (!response.ok) {
    return Promise.reject({message: 'xxx', response});
  }
})
```
